helmDefaults:
  atomic: true
  wait: true

helmfiles:
  - path: metrics-server/helmfile.yaml
  - path: grafana-prometheus/helmfile.yaml
  - path: falco/helmfile.yaml
  - path: falco-exporter/helmfile.yaml
