repositories:
- name: falcosecurity
  url: https://falcosecurity.github.io/charts

releases:
- name: falco-exporter
  namespace: falco
  chart: falcosecurity/falco-exporter
  version: 0.6.2
  values:
    - values.yaml
