repositories:
- name: falcosecurity
  url: https://falcosecurity.github.io/charts

releases:
- name: falco
  namespace: falco
  chart: falcosecurity/falco
  version: 1.16.2
  values:
    - values.yaml
