falco:
  grpc:
    enabled: True

  grpcOutput:
    enabled: True

  jsonOutput: true
  jsonIncludeOutputProperty: true
  httpOutput:
    enabled: true
    url: "http://falcosidekick:2801/"

  auditLog:
    enabled: true
    dynamicBackend:
      enabled: true

falcosidekick:
  enabled: true
  webui:
    enabled: true
